seed: 3407
epochs: 50
batch_size: 64
lr_backbone: 1.0e-4
lr_head: 5.0e-4  # 0.001 * (batch_size / 256) ** 0.5
weight_decay: 0.05
clip_value: 1.0
num_workers: 4
checkpoint_dir: checkpoints
device: cuda
